### PR TITLE
Add null check in `new-module-imports` rule (again)

### PR DESCRIPTION
**Pull request by bmish**
Fixes this test case:

```
new-module-imports › valid › for (let i = 0; i < 10; i++) { }

    TypeError: pp.body.some is not a function
    Occurred while linting <input>:1

      162 |   }
      163 |
    > 164 |   return pp.body.some(n => {
          |                  ^
      165 |     function containsInitSpecifier(specifiers) {
      166 |       return specifiers.some(s => {
      167 |         return s.local.name === name;

      at some (lib/utils/new-module.js:164:18)
      at isInitImportedFrom (lib/rules/new-module-imports.js:59:44)
```

Same issue as in #459. Caused by #450.

@dcyriller the null check does not seem like a great fix, even though it solves the immediate problem. Can you please investigate if there is a better fix for this?

### CODE REVIEW

**Comment by dcyriller** [comment]
@bmish I've a submitted a PR to check against node types. It should be a better fix to these issues.
